theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  date_format: "%Y-%m-%d"

description: Finish your tax return, and enjoy life!
#google_analytics: UA-187805015-1
google_analytics: G-L9YXPMD92X
title: ""
email: ""
author: ""
